name: Documentation Tests

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - 'emb-examples'
  pull_request:
  workflow_dispatch:

jobs:
  doctests:
    runs-on: ubuntu-latest
    services:
      redis-stack:
        image: redis/redis-stack-server:latest
        options: >-
          --health-cmd "redis-cli ping" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
        ports:
          - 6379:6379


    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            /var/cache/apt
          key: jedis-${{hashFiles('**/pom.xml')}}
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Configure Datadog Test Visibility
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: java
          service: jedis
          api_key: ${{ secrets.DATADOG_API_KEY }}
          site: datadoghq.eu
      - name: Configure Redis Check for Datadog Agent
        run: |
          sudo mkdir -p /etc/datadog-agent/conf.d/redisdb.d
          echo '
          init_config:

          instances:
            - host: localhost
              port: 6379
          ' | sudo tee /etc/datadog-agent/conf.d/redisdb.d/conf.yaml
      - name: Run doctests
        run: |
          mvn clean -Pdoctests test
